name: Deploy Plugin

on:
  push:
    tags:
      - '*.*.*'

jobs:

  tags-check:
    name: Check tagged branch
    if: contains(github.ref, 'tags/')
    uses: tarosky/workflows/.github/workflows/check-tag-in-branch.yml@main
    with:
      allowed_branch: "main"

  release:
    name: Publish Release
    needs: tags-check
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/tarosky/viewport-grid/releases
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Plugin
        run: bash bin/build.sh ${{ github.ref }}

      - name: Zip Archive
        run: |
          mkdir ${{ github.event.repository.name }}
          rsync -av --exclude=${{ github.event.repository.name }} --exclude-from=.distignore ./ ./${{ github.event.repository.name }}/
          zip -r ./${{ github.event.repository.name }}.zip ./${{ github.event.repository.name }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
